LITE-28082 List tasks in scope of a deployment request
cloudblue/connect-extension-xvs pull request #58
Opened 2023-07-28 13:29 UTC by jonatrios

2023-07-28 14:25 UTC, akodelia approved these changes

2023-07-31 10:46 UTC, akodelia approved these changes

2023-07-31 10:47 UTC, Hairash requested changes

2023-07-31 11:08 UTC, jonatrios commented on connect_ext_ppr/webapp.py
> +            .first()
done!

2023-07-31 12:06 UTC, Hairash approved these changes

2023-07-31 12:08 UTC, merged